fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # carthage
  end

  def suite_id_beta
    "tech\\.median"
  end

  def suite_id_dev
    "t3ch\\.m3dian"
  end

  def files_with_suite_id
    project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
    
    return [
      File.join(project_dir, 'FocusPlan.xcodeproj', 'project.pbxproj'),
    ]
  end

  def rewrite_from_all(files, to)
    rewrite_files(files_with_suite_id, suite_id_dev, to)
    rewrite_files(files_with_suite_id, suite_id_beta, to)
  end

  def rewrite_files(files, from, to)
    rewrite_exact_files(files, from, to)
  end

  def rewrite_exact_files(files, from, to)
    files.each do |file|
      Actions.sh("sed -i '' 's/#{from}/#{to}/g' #{file}")
    end
  end

  lane :enable_trial do
    project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
    file = File.join(project_dir, 'FocusPlan', 'Config.swift')
    from = "isTrial = false"
    to = "isTrial = true"

    Actions.sh("sed -i '' 's/#{from}/#{to}/g' #{file}")
  end

  lane :disable_trial do
    project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
    file = File.join(project_dir, 'FocusPlan', 'Config.swift')
    from = "isTrial = true"
    to = "isTrial = false"

    Actions.sh("sed -i '' 's/#{from}/#{to}/g' #{file}")
  end

  # lane :switch_to_beta do
  #   rewrite_from_all(files_with_suite_id, suite_id_beta)
  # end

  # lane :switch_to_dev do
  #   rewrite_from_all(files_with_suite_id, suite_id_dev)
  # end

  lane :bump do
    increment_build_number
  end

  lane :trial do
    number = increment_build_number

    enable_trial

    project_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))

    build_dir = File.join(project_dir, "build")

    system("rm -rf #{build_dir}")

    # switch_to_beta

    build_dir = gym(
      scheme: "FocusPlan",
      output_directory: build_dir,
      codesigning_identity: "Developer ID Application: Median Tech, s.r.o. (Q4C48EKH9Z)",
      archive_path: File.join(project_dir, "build", "archive"),
      provisioning_profile_path: File.join(project_dir, "XC_OSX_techmedianFocusPlan.provisionprofile")
    )

    app_path = File.join(build_dir, "FocusPlan.app")

    build_dir = File.dirname(app_path)
    dsym_path = File.join(build_dir, "FocusPlan.app.dSYM.zip")

    # switch_to_dev

    # Deploy locally...
    # Actions.sh "killall FocusPlan || date"
    # Actions.sh "rm -rf /Applications/FocusPlan.app"
    # puts "Copying " + "cp #{app_path} /Applications"

    # system("open #{build_dir}")

    # zip_path = app_path + ".zip"
    # app_filename = File.basename(app_path)
    # Actions.sh("pushd #{build_dir} && zip -y -r #{zip_path} #{app_filename}/* && popd")

    # hockey(
    #   :api_token => "aec6fd6f1ad54a5686fca0b5a7916710",
    #   :ipa => zip_path,
    #   :dsym => dsym_path
    # )


    # Prepare a DMG

    build_template_dir = File.join(project_dir, "build_template")

    Actions.sh("cp #{File.join(build_template_dir, "info.json")} #{build_dir}")
    Actions.sh("cp #{File.join(build_template_dir, "background.png")} #{build_dir}")

    dmg_name = "FocusPlan_Trial_build#{number}.dmg"

    Actions.sh("appdmg #{File.join(build_dir, "info.json")} '#{File.join(build_dir, dmg_name)}'")

    Actions.sh("gsutil cp -r '#{File.join(build_dir, dmg_name)}' gs://focusplan-74d7e.appspot.com/")
    Actions.sh("gsutil acl ch -u AllUsers:R 'gs://focusplan-74d7e.appspot.com/#{dmg_name}'")

    puts "https://storage.googleapis.com/focusplan-74d7e.appspot.com/#{dmg_name}"

    # gsutil cp script_installer/$FILENAME gs://focusplan-74d7e.appspot.com/
# gsutil acl ch -u AllUsers:R gs://focusplan-74d7e.appspot.com/$FILENAME

    disable_trial

    # Actions.sh "mv #{app_path} /Applications"
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

